name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          # Build the Docker image
          docker build -t ghcr.io/${{ github.repository_owner }}/kube-aws-istio:${{ github.ref_name }} .

          # Push the Docker image
          docker push ghcr.io/${{ github.repository_owner }}/kube-aws-istio:${{ github.ref_name }}
